services:
  ai:
    build:
      context: .
    ports:
      - "7860:7860"
      - "11435:11434"
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - ./static:/app/static
    working_dir: /app
